// <auto-generated />
using System;
using CarShop.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarShop.DAL.Migrations
{
    [DbContext(typeof(CarDbContext))]
    [Migration("20240402162818_DataSeed")]
    partial class DataSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarShop.DAL.Entities.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Brand = "Toyota",
                            Model = "Corolla",
                            Price = 15000m,
                            StoreId = 1,
                            Year = 2019
                        },
                        new
                        {
                            Id = 2,
                            Brand = "Toyota",
                            Model = "Camry",
                            Price = 20000m,
                            StoreId = 1,
                            Year = 2020
                        },
                        new
                        {
                            Id = 3,
                            Brand = "Honda",
                            Model = "Civic",
                            Price = 14000m,
                            StoreId = 2,
                            Year = 2018
                        },
                        new
                        {
                            Id = 4,
                            Brand = "Honda",
                            Model = "Accord",
                            Price = 18000m,
                            StoreId = 2,
                            Year = 2019
                        });
                });

            modelBuilder.Entity("CarShop.DAL.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Main St",
                            Name = "Toyota of Orlando",
                            Phone = "407-555-1212"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Main St",
                            Name = "Honda of Orlando",
                            Phone = "407-555-1213"
                        });
                });

            modelBuilder.Entity("CarShop.DAL.Entities.Car", b =>
                {
                    b.HasOne("CarShop.DAL.Entities.Store", "Store")
                        .WithMany("Cars")
                        .HasForeignKey("StoreId");

                    b.Navigation("Store");
                });

            modelBuilder.Entity("CarShop.DAL.Entities.Store", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
